# This is a basic workflow to help you get started with Actions

name: Check run on arch

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name : Checkout
      uses: actions/checkout@v3

      # Runs a single command using the runners shell
    - name : Build system
      uses: uraimo/run-on-arch-action@v2.5.0
      with:
        arch: armv7
        distro: ubuntu-latest
        githubToken: ${{ github.token }}
        install: |
            echo "Install packages"
            apt-get update && apt-get install python3
        run: |
          echo "system installed"
      
    - name : Build system (qemu)
      uses: uraimo/run-on-arch-action@v2.5.0
      with:
        arch: armv7
        distro: ubuntu-latest
        githubToken: ${{ github.token }}
        install: |
            echo "Install packages"
            apt-get update && apt-get install python3
        run: |
          python3 --version
          
          