name: Pass variable to install

on:
  workflow_dispatch:

env:
  Vcmake: 3.26.3

jobs:
  build:
    runs-on: ubuntu-22.04


    strategy:
      fail-fast: false
      matrix:
        include:
        - { qemu_arch: armv7,   appimage_arch: armhf }
        - { qemu_arch: aarch64, appimage_arch: aarch64 }

    steps:

    - name : test matrix
      uses: uraimo/run-on-arch-action@v2.6.0
      with:
        arch: armv7
        distro: ubuntu22.04
        githubToken: ${{ github.token }}
        install: |
            case "${{ matrix.qemu_arch }}" in 
              aarch64)
                apt-get update && apt-get -y install tar wget curl;
                curl -sSL https://github.com/Kitware/CMake/releases/download/v"${{ env.Vcmake }}"/cmake-"${{ env.Vcmake }}"-linux-aarch64.tar.gz -o cmake.tar.gz;
                tar xf cmake.tar.gz;
                ;;
              armv7)
                echo " armv7";
                ;;
              esac

        run: |
          echo "system installed"