name: Pass variable to install

on:
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-22.04


    strategy:
      fail-fast: false
      matrix:
        include:
        - { qemu_arch: armv7,   appimage_arch: armhf }
        - { qemu_arch: aarch64, appimage_arch: aarch64 }

    env:
      env_test: 3.26.3
      run_test: |
        case "${{ matrix.qemu_arch }}" in 
          aarch64)
            echo "This is arch64"
            ;;
          armv7)
            echo "This is armv7"
            ;;
          esac
          echo "this is ${{ jobs.build.env.env_test }}"

    steps:

    - name : test matrix
      uses: uraimo/run-on-arch-action@v2.5.0
      with:
        arch: armv7
        distro: ubuntu22.04
        githubToken: ${{ github.token }}
        install: |
            ${{ jobs.build.env.run_test }}
        run: |
          echo "system installed"