name: Check container build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04


    strategy:
      fail-fast: false
      matrix:
        include:
          - qemu_arch: armv7
            qemu_distro: ubuntu22.04
          - qemu_arch: aarch64
            qemu_distro: ubuntu22.04

    steps:

    - name : Step 1
      uses: uraimo/run-on-arch-action@v.2.5.1
      with:
        arch: ${{ matrix.qemu_arch }}
        distro: ${{ matrix.qemu_distro }}
        githubToken: ${{ github.token }}
        install: |
            case "${{ matrix.qemu_arch }}" in 
              aarch64)
                echo " aarch64";
                apt-get update && apt-get -y install tar wget curl;
                ;;
              armv7)
                echo " armv7";
                apt-get update && apt-get -y install tar wget curl;
                ;;
              esac

        run: |
          echo "system installed"
