name: Pass variable to install

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
        - { qemu_arch: armv7,   appimage_arch: armhf }
        - { qemu_arch: aarch64, appimage_arch: aarch64 }

    steps:

    - name : test matrix
      uses: uraimo/run-on-arch-action@v2.5.0
      with:
        arch: armv7
        distro: ubuntu22.04
        githubToken: ${{ github.token }}
        install: |
            case "${{ matrix.qemu_arch }}" in 
              aarch64)
               echo "This is arch64"
              armv7*)
                echo "This is armv7"
                ;;
              esac
        run: |
          echo "system installed"